# Generated by Django 4.1.6 on 2023-03-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Author', models.CharField(max_length=40)),
                ('Main', models.CharField(max_length=100)),
                ('Text', models.CharField(max_length=2000)),
                ('Tegs', models.CharField(max_length=300)),
            ],
        ),
    ]
