# Generated by Django 4.1.6 on 2023-05-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_date_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=100)),
                ('Patronymic', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Grope', models.CharField(default='none', max_length=255)),
            ],
        ),
    ]
